Update mods
Keviro/community-server-docs pull request #122
Opened 2024-09-25 15:22 UTC by TheBjoRedCraft

Update mods - add flashback

2024-09-27 17:40 UTC, twisti-dev requested changes

2024-09-27 17:40 UTC, twisti-dev commented on Writerside/topics/cross-server/features/friend-system.md
Ich nehme mal an diese file gehört nicht in den commit?

2024-09-27 21:13 UTC, TheBjoRedCraft commented on Writerside/topics/cross-server/features/friend-system.md
das ist in dem feat(docs): add flashback to verified mods nicht drin

2024-09-27 21:14 UTC, TheBjoRedCraft commented on Writerside/topics/cross-server/features/friend-system.md
aber hier sind ja sowieso 13 commits mehr drin keine ahnung warum 
![image](https://github.com/user-attachments/assets/f1ebb73a-fe58-4c50-80ba-4ab3ec98664b)

2024-09-27 21:14 UTC, TheBjoRedCraft commented on Writerside/topics/cross-server/features/friend-system.md
siehe https://github.com/Keviro/community-server-docs/pull/122/commits

2024-09-28 10:59 UTC, twisti-dev commented on Writerside/topics/cross-server/features/friend-system.md
Keine Ahnung die ist halt aber mit in dem branch drin. So kann ich das nicht mergen

2024-09-28 11:35 UTC, closed without merging

2024-09-28 23:44 UTC, twisti-dev commented
Also es ging mir jetzt nicht darum sie gar nicht zu mergen. Ich kann sie nur so mit der file nicht mergen - die müsste halt raus

2024-09-28 23:46 UTC, TheBjoRedCraft commented
Jaja alles gut, ich mach das morgen neu

2024-09-30 05:50 UTC, twisti-dev commented
Achso