Rework rules
Keviro/community-server-docs pull request #151
Opened 2024-12-06 21:25 UTC by ammodev

This pull request includes significant updates to the `Writerside/topics/rules/rules.md` file, focusing on clarifying and refining server rules for better readability and enforcement. The most important changes include modifications to the rules on griefing, game modifications, player behavior, and trading.

Clarifications and refinements:

* **Griefing**: Updated the language to clarify that any destruction or theft from other players will result in an immediate ban and emphasized the need for explicit permission for any changes or usage of private areas. [[1]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L21-L50) [[2]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L105-L131)

* **Game Modifications**: Revised the rules to specify that any unauthorized modifications, including those that automate player activities or bypass anti-cheat measures, are strictly prohibited, and clarified the consequences of using such modifications. [[1]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L21-L50) [[2]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L105-L131)

* **Player Behavior**: Enhanced the guidelines on respectful behavior, including detailed rules for voice chat usage and the handling of conflicts, emphasizing the importance of politeness and respect among players. [[1]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L66-R95) [[2]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L144-R180)

* **Boosting and IRL Trading**: Strengthened the prohibition on multiple accounts and clarified the restrictions on trading, including the consequences of exploiting server mechanics for personal gain. [[1]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L66-R95) [[2]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L144-R180)

* **Authority of Moderators and Admins**: Reiterated that moderators and admins have the final say in all matters, even if their decisions contradict the official rules, and requested players to comply without engaging in lengthy discussions. [[1]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L66-R95) [[2]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L144-R180)

2024-12-07 11:38 UTC, twisti-dev requested changes
Insgesammt so eine 8/10 👍

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   Ausschluss vom Server.
```suggestion
   von anderen Spielern zerstörst oder andere Spieler bestiehlst, wirst du sofort
   vom Server ausgeschlossen.
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   umgehen oder auszutricksen, nicht zulässig.
```suggestion
   Hardware oder sonstige Möglichkeiten handelt. Ebenso sind Modifikationen zur Umgehung oder Täuschung von Anti-Cheat-Maßnahmen nicht erlaubt.
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   nicht, [werft einen Blick auf die Liste geprüfter Mods][verified-mods] oder [kontaktiert den Support][support].
```suggestion
   Bereits das Betreten des Servers mit einer unerlaubten Modifikation gilt als Verstoß und kann zum
   Ausschluss führen. Wenn also unklar ist, ob eine Modifikation erlaubt ist, verwendet sie
   nicht, [schaut in die Liste geprüfter Modifikationen][verified-mods] oder [kontaktiert den Support][support].
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   Beleidigungen, Anfeindungen, Scamming oder Trolling, wird nicht geduldet.
```suggestion
   Behandelt andere Spieler stets höflich und respektvoll. **Belästigungen jeglicher Art**, sei es durch
   Beleidigungen, Anfeindungen, Scamming oder Trolling, werden von uns nicht geduldet.
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +        - **Verboten:** Überall sonst, insbesondere in alltäglichen Sprachchats oder um andere Spieler zu trollen.
```suggestion
        - **Verboten:** Überall sonst, insbesondere in alltäglichen Sprachchats oder zum Trollen anderer Spieler.
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   > Offene Streitigkeiten werden nicht toleriert, und wir behalten uns vor, Spieler für solche Konflikte vorübergehend
```suggestion
   > Offene Streitigkeiten werden nicht toleriert, und wir behalten uns das Recht vor, Spieler wegen solcher Konflikte vorübergehend
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +5. **Boosting und IRL Trading sind strikt untersagt.**
```suggestion
5. **Boosting und IRL-Trading sind strengstens verboten.**  
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   Jeder Spieler darf lediglich **einen Account** besitzen. Die Nutzung von Zweit-Accounts zum Farmen von Ressourcen,
```suggestion
   Jeder Spieler darf lediglich **einen Account** besitzen. Die Nutzung von Zweitaccounts zum Farmen von Ressourcen,
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   Geld oder anderen Vorteilen ist verboten.
```suggestion
   Geld oder anderen Vorteilen ist untersagt.
```

2024-12-07 11:38 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   Freunde diese Mechaniken ausnutzen, wird es für beide in einem Ausschluss enden.
```suggestion
   Des Weiteren ist es nicht erlaubt, dass Spieler oder ihre Freunde den Server nur betreten,
   um beispielsweise Items aus einem Adventskalender an andere zu übergeben und dann sofort wieder disconnecten, ohne eine
   tatsächliche Absicht zu haben, aktiv am Spielgeschehen teilzunehmen. Sollte auffallen, dass Spieler und/oder deren
   Freunde diese Mechaniken ausnutzen, wird dies mit einem Ausschluss für beide geahndet.
```

2024-12-07 13:06 UTC, Keviro commented on Writerside/topics/rules/rules.md
> +   Ausschluss vom Server.
Ich finde `droht ein sofortiger Ausschluss vom Server` hört sich besser an ehrlich gesagt

2024-12-07 14:36 UTC, twisti-dev commented on Writerside/topics/rules/rules.md
> +   Ausschluss vom Server.
Bei "drohen" finde ich, dass es so klingt, als ob es nicht immer passiert - aber wir bannen ja immer

2024-12-16 12:20 UTC, twisti-dev approved these changes

2024-12-20 19:13 UTC, merged