fix(docs): update features.md // update changed-vanilla.mechanics.md
Keviro/community-server-docs pull request #152
Opened 2024-12-11 22:16 UTC by JoField08

added snippet to util.md // included snipped in features.md and changed-vanilla-mechanics.md // added subcategory for the util

2024-12-13 14:34 UTC, twisti-dev requested changes

2024-12-13 14:34 UTC, twisti-dev commented on Writerside/topics/reusablecontent/util.md
> +einem Ausschluss des Servers führen.**
hier auch?

2024-12-15 01:01 UTC, JoField08 commented on Writerside/topics/reusablecontent/util.md
> +einem Ausschluss des Servers führen.**
ctrl + alt + L

2024-12-15 01:01 UTC, JoField08 commented on Writerside/topics/reusablecontent/util.md
> +herunterladen.**
ctrl + alt + L

2024-12-16 09:24 UTC, JoField08 commented on Writerside/topics/reusablecontent/util.md
> +herunterladen.**
https://github.com/Keviro/community-server-docs/pull/152/commits/eec57fe91080bee48432099afe01c269066073b0

2024-12-16 09:24 UTC, JoField08 commented on Writerside/topics/reusablecontent/util.md
> +einem Ausschluss des Servers führen.**
https://github.com/Keviro/community-server-docs/pull/152/commits/eec57fe91080bee48432099afe01c269066073b0

2024-12-16 12:19 UTC, twisti-dev approved these changes

2024-12-16 12:19 UTC, merged