fix(docs): update verified-mods.md
Keviro/community-server-docs pull request #153
Opened 2024-12-11 22:53 UTC by JoField08

2024-12-11 22:54 UTC, JoField08 commented
Ich glaube das ist jetzt besser so, weil das alle Spieler immer nur als "einzig erlaubte Mods angesehen haben"

2024-12-13 14:30 UTC, twisti-dev requested changes

2024-12-13 14:30 UTC, twisti-dev commented on Writerside/topics/rules/mods/mods/verified-mods.md
> +Bitte beachtet, dass **auch andere Modifikationen erlaubt** sind, welche **nicht gegen das [Regelwerk](rules.md) verstoßen**.
```suggestion
Die folgende Liste enthält Modifikationen enthalten, die ohne Bedenken auf dem Server verwendet werden können.
Die Modifikationen wurden vom Team getestet und sind mit dem Server kompatibel.\
Bitte beachtet, dass **auch andere Modifikationen erlaubt** sind, die **nicht gegen das [Regelwerk](rules.md) verstoßen**.
```

2024-12-13 14:30 UTC, twisti-dev commented on Writerside/topics/rules/mods/mods/verified-mods.md
> +    - Die Verwendung von **EasyPlace** oder dem **Printer** ist jedoch **untersagt** und kann zu einem **Ausschluss vom Server** führen.
```suggestion
    - Die Verwendung von **EasyPlace** oder dem **Printer** ist jedoch ** strengstens untersagt** und kann zum **Ausschluss vom Server** führen. 
```

2024-12-13 14:30 UTC, twisti-dev commented on Writerside/topics/rules/mods/mods/verified-mods.md
> +  - **Without using EasyPlace or Printer!**
```suggestion
  - However, the use of **EasyPlace** or the **Printer** is **strictly prohibited** and may lead to **exclusion from the server**.
```

2024-12-15 00:56 UTC, JoField08 commented on Writerside/topics/rules/mods/mods/verified-mods.md
> +Bitte beachtet, dass **auch andere Modifikationen erlaubt** sind, welche **nicht gegen das [Regelwerk](rules.md) verstoßen**.
"Die folgende Liste enthält Modifikationen enthalten [...]" ??

2024-12-15 01:05 UTC, JoField08 commented on Writerside/topics/rules/mods/mods/verified-mods.md
> +Bitte beachtet, dass **auch andere Modifikationen erlaubt** sind, welche **nicht gegen das [Regelwerk](rules.md) verstoßen**.
https://github.com/Keviro/community-server-docs/pull/153/commits/39e04a45042be858827906217014b4b684911441

2024-12-16 12:18 UTC, twisti-dev approved these changes

2024-12-16 12:18 UTC, merged