fix(docs): update troubleshooting.md
Keviro/community-server-docs pull request #154
Opened 2024-12-16 15:30 UTC by JoField08

added chat-issues tab

2024-12-16 17:24 UTC, twisti-dev requested changes

2024-12-16 17:24 UTC, twisti-dev commented on Writerside/topics/questions/troubleshooting.md
> +<tab title="Probleme mit dem Chat" id="chat-issues">
```suggestion
<tab title="Chat-Probleme" id="chat-issues">
```
Das ist halt jetzt schon richtig arsch am Handy

2024-12-16 17:24 UTC, twisti-dev commented on Writerside/topics/questions/troubleshooting.md
> +2. **Einstellungen:** Stelle sicher, dass die Chateinstellungen richtig konfiguriert sind. Überprüfe, ob die Einstellung `Nur sicheren Chat anzeigen` ausgeschalten ist.
Vielleicht noch irgendwie das wiki einbinden https://de.minecraft.wiki/w/Men%C3%BC/Optionen/Chateinstellungen
Und kann es nicht auch sein, dass der User einfach Chat auf "Versteckt" oder "Nur Befehle anzeigen" hat

2024-12-16 17:24 UTC, twisti-dev commented on Writerside/topics/questions/troubleshooting.md
> +   zu vermeiden. Solltest du Modifikationen für den Chat installiert haben, lösche diese.
"Solltest du Modifikationen für den Chat installiert haben, lösche diese."
Ist das nicht ein bisschen unnötig? Das geht doch gar nicht im normalen Vanilla Client ohne Mods

2024-12-16 17:24 UTC, twisti-dev commented on Writerside/topics/questions/troubleshooting.md
> +5. **Aus- und Einloggen:** Logge dich im Minecraft-Launcher mit deinem Microsoft Konto einmal aus und wieder ein.
```suggestion
5. **Aus- und Einloggen:** Logge dich im Minecraft-Launcher mit deinem Microsoft-Konto einmal aus und wieder ein.
```

2024-12-16 18:57 UTC, JoField08 commented on Writerside/topics/questions/troubleshooting.md
> +   zu vermeiden. Solltest du Modifikationen für den Chat installiert haben, lösche diese.
Nein das ist nicht unnötig

2024-12-16 18:58 UTC, JoField08 commented on Writerside/topics/questions/troubleshooting.md
> +5. **Aus- und Einloggen:** Logge dich im Minecraft-Launcher mit deinem Microsoft Konto einmal aus und wieder ein.
... hab das von dir kopiert und vertraut...

2024-12-16 19:01 UTC, JoField08 commented on Writerside/topics/questions/troubleshooting.md
> +2. **Einstellungen:** Stelle sicher, dass die Chateinstellungen richtig konfiguriert sind. Überprüfe, ob die Einstellung `Nur sicheren Chat anzeigen` ausgeschalten ist.
https://github.com/Keviro/community-server-docs/pull/154/commits/5252e6b43690a7b5fcd1d32381e4abd41fb1962a

2024-12-18 11:14 UTC, twisti-dev commented on Writerside/topics/questions/troubleshooting.md
> +   zu vermeiden. Solltest du Modifikationen für den Chat installiert haben, lösche diese.
Und wie installiert man Chat Mods, wenn man keine Mods benutzen soll?

2024-12-18 11:15 UTC, twisti-dev commented on Writerside/topics/questions/troubleshooting.md
> +5. **Aus- und Einloggen:** Logge dich im Minecraft-Launcher mit deinem Microsoft Konto einmal aus und wieder ein.
Ja hättest du mal selber gedacht

2024-12-18 16:21 UTC, JoField08 commented on Writerside/topics/questions/troubleshooting.md
> +   zu vermeiden. Solltest du Modifikationen für den Chat installiert haben, lösche diese.
https://github.com/Keviro/community-server-docs/pull/154/commits/795454ceb7f3cdfe15b68d43f926e96316b13174

2024-12-18 19:00 UTC, merged