fix(docs): update events.md
Keviro/community-server-docs pull request #164
Opened 2024-12-25 21:57 UTC by JoField08

rewrite

2024-12-25 21:57 UTC, JoField08 commented
@twisti-dev

2024-12-30 22:13 UTC, twisti-dev requested changes

2024-12-30 22:13 UTC, twisti-dev commented on Writerside/topics/survival-server/specials/specials/events/events.md
> +Dieses dauert **20 Minuten**. Während dieses Events besteht eine erhöhte Chance auf Mending, Soulbound, Totems sowie weiteren [Trödel- und Schatzfängen](https://minecraft.wiki/w/Fishing).
```suggestion
An jeden <tooltip term="Wochenende">Wochenendtagen</tooltip> findet um **20:00 Uhr** ein Angel-Event statt,
welches **20 Minuten** dauert. Während dieses Events besteht eine erhöhte Chance auf Mending, Soulbound, Totems sowie weiteren [Trödel- und Schatzfängen](https://minecraft.wiki/w/Fishing).
```

2024-12-30 22:13 UTC, twisti-dev commented on Writerside/topics/survival-server/specials/specials/events/events.md
> +Dieses dauert **20 Minuten**. Während diesem Event wird die Abbaugeschwindigkeit erhöht, indem du den Effekt `Eile X` erhältst.
```suggestion
An allen <tooltip term="Wochentage">Wochentagen</tooltip> findet um **20:00 Uhr** ein Mining-Event statt,
welches **20 Minuten** dauert. Während diesem Event wird die Abbaugeschwindigkeit erhöht, indem du den Effekt `Eile X` erhältst.
```

2024-12-30 22:24 UTC, merged