feat(docs)!: edited support page
Keviro/community-server-docs pull request #50
Opened 2024-07-07 08:46 UTC by JoField08

2024-07-07 12:39 UTC, twisti-dev requested changes

2024-07-07 12:39 UTC, twisti-dev commented on Writerside/topics/support.md
> +<procedure>
Warum ist hier procedure wenn danach keine steps benutzt zum nummerieren? Dann muss man das nicht machen

2024-07-07 12:39 UTC, twisti-dev commented on Writerside/topics/survival-server/support/support/support.md
> +<procedure>
Warum ist das eine Procedur? Einfach eine Definition nehmen https://www.jetbrains.com/help/writerside/lists.html#definition_lists

2024-07-08 19:32 UTC, JoField08 commented on Writerside/topics/survival-server/support/support/support.md
> +<procedure>
und halt diesem komischen Ramen drumrum

2024-07-10 17:27 UTC, closed without merging

2024-07-10 17:27 UTC, JoField08 commented
#52