fix(docs): changed support button to donate button
Keviro/community-server-docs pull request #77
Opened 2024-08-06 16:04 UTC by JoField08

2024-08-06 16:05 UTC, twisti-dev approved these changes

2024-08-06 16:07 UTC, twisti-dev requested changes

2024-08-06 16:07 UTC, twisti-dev commented on Writerside/cfg/buildprofiles.xml
> +        <download-title>Donate</download-title>
```suggestion
        <download-title>Spenden</download-title>
```
Deutsche Dokumentation und so

2024-08-06 16:08 UTC, twisti-dev approved these changes

2024-08-07 19:40 UTC, ammodev approved these changes

2024-08-09 14:31 UTC, closed without merging