fix(docs): update civ- event page
Keviro/community-server-docs pull request #98
Opened 2024-08-31 16:17 UTC by JoField08

set state to event-held

2024-08-31 22:24 UTC, twisti-dev requested changes

2024-08-31 22:24 UTC, twisti-dev commented on Writerside/topics/civilisation-event.md
> -<secondary-label ref="civilisation-mc-version" />
Das kann da bleiben

2024-08-31 22:25 UTC, twisti-dev commented on Writerside/topics/civilisation-event.md
> -<secondary-label ref="civilisation-mc-version" />
Also nur 2. Keine Ahnung warum er beide ausgewählt hat

2024-09-01 14:37 UTC, JoField08 commented on Writerside/topics/civilisation-event.md
> -<secondary-label ref="civilisation-mc-version" />
https://github.com/Keviro/community-server-docs/pull/98/commits/164aaea6352591477bc486c76b85b6a066e8ead9

2024-09-01 14:48 UTC, twisti-dev approved these changes

2024-09-01 14:48 UTC, merged